"""added tags and updated models

Revision ID: 2e8107b66585
Revises: a39689c7a6b0
Create Date: 2026-07-04 16:55:30.176129

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2e8107b66585"
down_revision: Union[str, Sequence[str], None] = "a39689c7a6b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # 1. Create the custom Enum type in Postgres manually FIRST
    op.execute("CREATE TYPE role AS ENUM ('user', 'admin');")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "book_tag",
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("book_id", "tag_id"),
    )
    op.alter_column(
        "books", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "books", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "reviews",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "reviews",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "users", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###

    # 2. Alter the 'role' column using safe, raw PostgreSQL commands
    op.execute("ALTER TABLE users ALTER COLUMN role DROP DEFAULT;")
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE role USING role::text::role;")
    op.execute("ALTER TABLE users ALTER COLUMN role SET DEFAULT 'user'::role;")


def downgrade() -> None:
    """Downgrade schema."""

    # 1. Revert the 'role' column back to a standard string
    op.execute("ALTER TABLE users ALTER COLUMN role DROP DEFAULT;")
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE VARCHAR USING role::text;")
    op.execute(
        "ALTER TABLE users ALTER COLUMN role SET DEFAULT 'user'::character varying;"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "users", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "reviews",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "reviews",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "books", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "books", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.drop_table("book_tag")
    op.drop_table("tags")
    # ### end Alembic commands ###

    # 2. Drop the custom Enum type during rollback
    op.execute("DROP TYPE role;")
